# Generated by Django 3.0 on 2022-01-25 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginformapp', '0002_signupdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUpData',
        ),
    ]
